[package]
name = "aubrieta_io"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aubrieta_foundation = { path = "../aubrieta_foundation" }
aubrieta_document = { path = "../aubrieta_document" }
aubrieta_geometry = { path = "../aubrieta_geometry" }
aubrieta_color = { path = "../aubrieta_color" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
zip = "8.6.0"
krilla = "0.8.2"

[dev-dependencies]
proptest = "1"
