[package]
name = "petunia_design_document"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
petunia_design_color = { path = "../petunia_design_color" }
petunia_design_foundation = { path = "../petunia_design_foundation" }
petunia_design_geometry = { path = "../petunia_design_geometry" }
petunia_design_raster = { path = "../petunia_design_raster" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest = "1.11.0"
