[package]
name = "aubrieta_ui_gpui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aubrieta_foundation = { path = "../aubrieta_foundation" }
aubrieta_document = { path = "../aubrieta_document" }
aubrieta_application = { path = "../aubrieta_application" }
aubrieta_geometry = { path = "../aubrieta_geometry" }
aubrieta_color = { path = "../aubrieta_color" }
aubrieta_raster = { path = "../aubrieta_raster" }
aubrieta_resources = { path = "../aubrieta_resources" }
aubrieta_platform = { path = "../aubrieta_platform" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest = "1.11.0"
