#!/usr/bin/env python3
"""Project the semantic JSON catalog into the native QML token component."""
import json
from pathlib import Path

root = Path(__file__).resolve().parent
data = json.loads((root / "design-tokens.json").read_text())
lines = ["// Generated by generate_theme.py from design-tokens.json.",
         "pragma ComponentBehavior: Bound", "import QtQuick", "", "QtObject {",
         '    property string appearance: "dark"', '    property real uiScale: 1',
         '    property string density: "comfortable"',
         '    readonly property bool light: appearance === "light"',
         '    readonly property bool contrast: appearance === "highContrast"']
for name, colors in data["color"].items():
    lines.append(f'    readonly property color {name}: contrast ? "{colors["highContrast"]}" : light ? "{colors["light"]}" : "{colors["dark"]}"')
target = data["component"]["target"]
lines.append(f'    readonly property int target: Math.round((density === "compact" ? {target["compact"]} : {target["comfortable"]})*uiScale)')
lines.append("}")
(root / "StudioTheme.qml").write_text("\n".join(lines) + "\n")
