// Generated by generate_theme.py from design-tokens.json.
pragma ComponentBehavior: Bound
import QtQuick

QtObject {
    property string appearance: "dark"
    property real uiScale: 1
    property string density: "comfortable"
    readonly property bool light: appearance === "light"
    readonly property bool contrast: appearance === "highContrast"
    readonly property color surround: contrast ? "#000000" : light ? "#E9EDF1" : "#161A1F"
    readonly property color panel: contrast ? "#000000" : light ? "#F7F8FA" : "#20262D"
    readonly property color raised: contrast ? "#000000" : light ? "#FFFFFF" : "#2A3038"
    readonly property color foreground: contrast ? "#F3F5F7" : light ? "#18212B" : "#F3F5F7"
    readonly property color secondary: contrast ? "#FFFFFF" : light ? "#57606A" : "#B2BBC5"
    readonly property color subtle: contrast ? "#FFFFFF" : light ? "#CCD3DA" : "#414B57"
    readonly property color controlBorder: contrast ? "#FFFFFF" : light ? "#6B7580" : "#83909E"
    readonly property color accent: contrast ? "#FFFF00" : light ? "#005EA8" : "#66D9EF"
    readonly property color selected: contrast ? "#000000" : light ? "#DFEDFA" : "#153D49"
    readonly property color selectedText: contrast ? "#FFFFFF" : light ? "#06447A" : "#D8F7FC"
    readonly property color error: contrast ? "#FFB4AB" : light ? "#B42318" : "#FFB4AB"
    readonly property int target: Math.round((density === "compact" ? 32 : 40)*uiScale)
}
