[package]
name = "petunia_design_application"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
petunia_design_foundation = { path = "../petunia_design_foundation" }
petunia_design_geometry = { path = "../petunia_design_geometry" }
petunia_design_document = { path = "../petunia_design_document" }
petunia_design_io = { path = "../petunia_design_io" }
petunia_design_render = { path = "../petunia_design_render" }
rstar = "0.12"
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
