[package]
name = "aubrieta_application"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aubrieta_foundation = { path = "../aubrieta_foundation" }
aubrieta_document = { path = "../aubrieta_document" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
