//! Canonical EN/pt-BR copy for Studio chrome and inspectors (ADR-012).
use crate::shell_strings::ShellString;

pub const STUDIO_STRINGS: &[ShellString] = &[
    ShellString { id: "ptnd.text.studio.accent", en: "Accent color", pt: "Cor de destaque" },
    ShellString { id: "ptnd.text.studio.action_history", en: "Action history", pt: "Histórico de ações" },
    ShellString { id: "ptnd.text.studio.add", en: "Add", pt: "Adicionar" },
    ShellString { id: "ptnd.text.studio.add_clip", en: "Add clip", pt: "Adicionar recorte" },
    ShellString { id: "ptnd.text.studio.add_contour", en: "Add contour", pt: "Adicionar contorno" },
    ShellString { id: "ptnd.text.studio.add_selected_color", en: "Add current color", pt: "Adicionar cor atual" },
    ShellString { id: "ptnd.text.studio.adjustments", en: "Adjustments", pt: "Ajustes" },
    ShellString { id: "ptnd.text.studio.align_bottom", en: "Bottom", pt: "Base" },
    ShellString { id: "ptnd.text.studio.align_center", en: "Center", pt: "Centro" },
    ShellString { id: "ptnd.text.studio.align_left", en: "Left", pt: "Esquerda" },
    ShellString { id: "ptnd.text.studio.align_right", en: "Right", pt: "Direita" },
    ShellString { id: "ptnd.text.studio.align_top", en: "Top", pt: "Topo" },
    ShellString { id: "ptnd.text.studio.alignment", en: "Alignment & geometry", pt: "Alinhamento e geometria" },
    ShellString { id: "ptnd.text.studio.alpha_channel", en: "Alpha", pt: "Alfa" },
    ShellString { id: "ptnd.text.studio.amount", en: "Amount", pt: "Quantidade" },
    ShellString { id: "ptnd.text.studio.antialias", en: "Canvas overlays", pt: "Sobreposições do canvas" },
    ShellString { id: "ptnd.text.studio.antialias_description", en: "Handles and guides remain interactive while previews render.", pt: "Alças e guias permanecem interativas durante a renderização das prévias." },
    ShellString { id: "ptnd.text.studio.appearance", en: "Appearance", pt: "Aparência" },
    ShellString { id: "ptnd.text.studio.apply", en: "Apply", pt: "Aplicar" },
    ShellString { id: "ptnd.text.studio.asset_library", en: "Document assets", pt: "Recursos do documento" },
    ShellString { id: "ptnd.text.studio.assets", en: "Assets", pt: "Recursos" },
    ShellString { id: "ptnd.text.studio.back", en: "Send to back", pt: "Enviar para trás" },
    ShellString { id: "ptnd.text.studio.background_tasks", en: "Background tasks", pt: "Tarefas em segundo plano" },
    ShellString { id: "ptnd.text.studio.backward", en: "Send backward", pt: "Recuar" },
    ShellString { id: "ptnd.text.studio.bake", en: "Bake", pt: "Fixar" },
    ShellString { id: "ptnd.text.studio.bake_geometry", en: "Bake geometry", pt: "Fixar geometria" },
    ShellString { id: "ptnd.text.studio.bake_transparency", en: "Bake transparency", pt: "Fixar transparência" },
    ShellString { id: "ptnd.text.studio.basic_ellipse", en: "Ellipse", pt: "Elipse" },
    ShellString { id: "ptnd.text.studio.basic_polygon", en: "Polygon", pt: "Polígono" },
    ShellString { id: "ptnd.text.studio.basic_rectangle", en: "Rectangle", pt: "Retângulo" },
    ShellString { id: "ptnd.text.studio.basic_star", en: "Star", pt: "Estrela" },
    ShellString { id: "ptnd.text.studio.bevel", en: "Bevel", pt: "Chanfro" },
    ShellString { id: "ptnd.text.studio.bezier", en: "Bézier", pt: "Bézier" },
    ShellString { id: "ptnd.text.studio.black", en: "Black", pt: "Preto" },
    ShellString { id: "ptnd.text.studio.black_more", en: "Black +", pt: "Preto +" },
    ShellString { id: "ptnd.text.studio.bleed", en: "Bleed", pt: "Sangria" },
    ShellString { id: "ptnd.text.studio.blue", en: "Blue", pt: "Azul" },
    ShellString { id: "ptnd.text.studio.blur", en: "Blur", pt: "Desfoque" },
    ShellString { id: "ptnd.text.studio.brush", en: "Brush", pt: "Pincel" },
    ShellString { id: "ptnd.text.studio.brush_color", en: "Brush color", pt: "Cor do pincel" },
    ShellString { id: "ptnd.text.studio.butt", en: "Butt", pt: "Reto" },
    ShellString { id: "ptnd.text.studio.cancel", en: "Cancel", pt: "Cancelar" },
    ShellString { id: "ptnd.text.studio.cap", en: "Cap", pt: "Extremidade" },
    ShellString { id: "ptnd.text.studio.channel", en: "Channel", pt: "Canal" },
    ShellString { id: "ptnd.text.studio.clear", en: "Clear completed", pt: "Limpar concluídas" },
    ShellString { id: "ptnd.text.studio.close_tab", en: "Close document", pt: "Fechar documento" },
    ShellString { id: "ptnd.text.studio.collapse", en: "Collapse panel", pt: "Recolher painel" },
    ShellString { id: "ptnd.text.studio.collapse_layer", en: "Collapse group", pt: "Recolher grupo" },
    ShellString { id: "ptnd.text.studio.color", en: "Color", pt: "Cor" },
    ShellString { id: "ptnd.text.studio.color_library", en: "Color library", pt: "Biblioteca de cores" },
    ShellString { id: "ptnd.text.studio.color_settings", en: "Edit color…", pt: "Editar cor…" },
    ShellString { id: "ptnd.text.studio.color_space", en: "Color model", pt: "Modelo de cor" },
    ShellString { id: "ptnd.text.studio.colors", en: "Colors", pt: "Cores" },
    ShellString { id: "ptnd.text.studio.constrain", en: "Constrain", pt: "Restringir" },
    ShellString { id: "ptnd.text.studio.cooler", en: "Cooler −0.1", pt: "Mais frio −0,1" },
    ShellString { id: "ptnd.text.studio.copy_style", en: "Copy style", pt: "Copiar estilo" },
    ShellString { id: "ptnd.text.studio.corners", en: "Corners", pt: "Cantos" },
    ShellString { id: "ptnd.text.studio.curve_points", en: "Curve points", pt: "Pontos da curva" },
    ShellString { id: "ptnd.text.studio.curves", en: "Convert to curves", pt: "Converter em curvas" },
    ShellString { id: "ptnd.text.studio.curves_adjustment", en: "Curves", pt: "Curvas" },
    ShellString { id: "ptnd.text.studio.cyan", en: "Cyan", pt: "Ciano" },
    ShellString { id: "ptnd.text.studio.decrease_amount", en: "Amount −10%", pt: "Quantidade −10%" },
    ShellString { id: "ptnd.text.studio.decrease_blur", en: "Blur −2", pt: "Desfoque −2" },
    ShellString { id: "ptnd.text.studio.delete", en: "Delete", pt: "Excluir" },
    ShellString { id: "ptnd.text.studio.diagnostics", en: "Diagnostics", pt: "Diagnóstico" },
    ShellString { id: "ptnd.text.studio.distance", en: "Distance", pt: "Distância" },
    ShellString { id: "ptnd.text.studio.document", en: "Document", pt: "Documento" },
    ShellString { id: "ptnd.text.studio.document_assets", en: "Document assets", pt: "Recursos do documento" },
    ShellString { id: "ptnd.text.studio.document_colors", en: "Document colors", pt: "Cores do documento" },
    ShellString { id: "ptnd.text.studio.document_histogram", en: "Document histogram", pt: "Histograma do documento" },
    ShellString { id: "ptnd.text.studio.drop_shadow", en: "Outer shadow", pt: "Sombra externa" },
    ShellString { id: "ptnd.text.studio.effects", en: "Layer effects", pt: "Efeitos de camada" },
    ShellString { id: "ptnd.text.studio.empty_layers", en: "Your layers will appear here", pt: "Suas camadas aparecerão aqui" },
    ShellString { id: "ptnd.text.studio.empty_layers_hint", en: "Draw on the canvas or place an image to start.", pt: "Desenhe no canvas ou insira uma imagem para começar." },
    ShellString { id: "ptnd.text.studio.empty_swatches", en: "No colors in this library yet.", pt: "Ainda não há cores nesta biblioteca." },
    ShellString { id: "ptnd.text.studio.empty_tasks", en: "No background tasks running.", pt: "Nenhuma tarefa em execução." },
    ShellString { id: "ptnd.text.studio.eraser", en: "Eraser", pt: "Borracha" },
    ShellString { id: "ptnd.text.studio.expand", en: "Expand panel", pt: "Expandir painel" },
    ShellString { id: "ptnd.text.studio.expand_geometry", en: "Expand 10 pt", pt: "Expandir 10 pt" },
    ShellString { id: "ptnd.text.studio.expand_layer", en: "Expand group", pt: "Expandir grupo" },
    ShellString { id: "ptnd.text.studio.exposure", en: "Exposure", pt: "Exposição" },
    ShellString { id: "ptnd.text.studio.favorite_swatches", en: "Favorite swatches", pt: "Amostras favoritas" },
    ShellString { id: "ptnd.text.studio.favorites", en: "Favorites", pt: "Favoritos" },
    ShellString { id: "ptnd.text.studio.file_exists", en: "File already exists", pt: "O arquivo já existe" },
    ShellString { id: "ptnd.text.studio.fill", en: "Fill", pt: "Preenchimento" },
    ShellString { id: "ptnd.text.studio.filled_icons", en: "Filled icons", pt: "Ícones preenchidos" },
    ShellString { id: "ptnd.text.studio.fit", en: "Fit document", pt: "Enquadrar documento" },
    ShellString { id: "ptnd.text.studio.forward", en: "Bring forward", pt: "Avançar" },
    ShellString { id: "ptnd.text.studio.freehand", en: "Freehand", pt: "Mão livre" },
    ShellString { id: "ptnd.text.studio.front", en: "Bring to front", pt: "Trazer para frente" },
    ShellString { id: "ptnd.text.studio.gradient", en: "Gradient", pt: "Gradiente" },
    ShellString { id: "ptnd.text.studio.green", en: "Green", pt: "Verde" },
    ShellString { id: "ptnd.text.studio.green_less", en: "Green −0.1", pt: "Verde −0,1" },
    ShellString { id: "ptnd.text.studio.group", en: "Group", pt: "Agrupar" },
    ShellString { id: "ptnd.text.studio.height", en: "Height", pt: "Altura" },
    ShellString { id: "ptnd.text.studio.hidden", en: "Hidden", pt: "Oculto" },
    ShellString { id: "ptnd.text.studio.hide_layer", en: "Hide layer", pt: "Ocultar camada" },
    ShellString { id: "ptnd.text.studio.hide_studio", en: "Hide Studio panels", pt: "Ocultar painéis do estúdio" },
    ShellString { id: "ptnd.text.studio.high_contrast", en: "High contrast", pt: "Alto contraste" },
    ShellString { id: "ptnd.text.studio.histogram", en: "Histogram", pt: "Histograma" },
    ShellString { id: "ptnd.text.studio.history", en: "History", pt: "Histórico" },
    ShellString { id: "ptnd.text.studio.history_file", en: "History & files", pt: "Histórico e arquivos" },
    ShellString { id: "ptnd.text.studio.history_policy", en: "Undo history uses a memory budget; saved files contain the current document.", pt: "O histórico de desfazer usa um orçamento de memória; os arquivos salvos contêm o documento atual." },
    ShellString { id: "ptnd.text.studio.hsl", en: "HSL", pt: "HSL" },
    ShellString { id: "ptnd.text.studio.hue", en: "Hue", pt: "Matiz" },
    ShellString { id: "ptnd.text.studio.icon_style", en: "Icon style", pt: "Estilo dos ícones" },
    ShellString { id: "ptnd.text.studio.image", en: "Image", pt: "Imagem" },
    ShellString { id: "ptnd.text.studio.increase_amount", en: "Amount +10%", pt: "Quantidade +10%" },
    ShellString { id: "ptnd.text.studio.increase_blur", en: "Blur +2", pt: "Desfoque +2" },
    ShellString { id: "ptnd.text.studio.increase_radius", en: "Radius +1", pt: "Raio +1" },
    ShellString { id: "ptnd.text.studio.inner_shadow", en: "Inner shadow", pt: "Sombra interna" },
    ShellString { id: "ptnd.text.studio.insert", en: "Insert", pt: "Inserir" },
    ShellString { id: "ptnd.text.studio.inset_geometry", en: "Inset 10 pt", pt: "Contrair 10 pt" },
    ShellString { id: "ptnd.text.studio.interaction_details", en: "Interaction", pt: "Interação" },
    ShellString { id: "ptnd.text.studio.interactive_fill", en: "Vector fill", pt: "Preenchimento vetorial" },
    ShellString { id: "ptnd.text.studio.intersect", en: "Intersect", pt: "Interseção" },
    ShellString { id: "ptnd.text.studio.invalid_hex", en: "Use #RRGGBB", pt: "Use #RRGGBB" },
    ShellString { id: "ptnd.text.studio.job_cancelled", en: "Cancelled", pt: "Cancelada" },
    ShellString { id: "ptnd.text.studio.job_completed", en: "Completed", pt: "Concluída" },
    ShellString { id: "ptnd.text.studio.job_failed", en: "Failed", pt: "Falhou" },
    ShellString { id: "ptnd.text.studio.job_queued", en: "Queued", pt: "Na fila" },
    ShellString { id: "ptnd.text.studio.job_running", en: "Running", pt: "Executando" },
    ShellString { id: "ptnd.text.studio.join", en: "Join", pt: "Junção" },
    ShellString { id: "ptnd.text.studio.language", en: "Interface language", pt: "Idioma da interface" },
    ShellString { id: "ptnd.text.studio.layers", en: "Layers", pt: "Camadas" },
    ShellString { id: "ptnd.text.studio.levels", en: "Levels", pt: "Níveis" },
    ShellString { id: "ptnd.text.studio.lightness", en: "Lightness", pt: "Luminosidade" },
    ShellString { id: "ptnd.text.studio.line", en: "Line", pt: "Linha" },
    ShellString { id: "ptnd.text.studio.linear", en: "Linear", pt: "Linear" },
    ShellString { id: "ptnd.text.studio.live_contour", en: "Live contour", pt: "Contorno ativo" },
    ShellString { id: "ptnd.text.studio.live_modifiers", en: "Live modifiers", pt: "Modificadores vivos" },
    ShellString { id: "ptnd.text.studio.lock_layer", en: "Lock layer", pt: "Bloquear camada" },
    ShellString { id: "ptnd.text.studio.margins", en: "Margins", pt: "Margens" },
    ShellString { id: "ptnd.text.studio.measure", en: "Measure", pt: "Medição" },
    ShellString { id: "ptnd.text.studio.measure_units", en: "Units", pt: "Unidades" },
    ShellString { id: "ptnd.text.studio.miter", en: "Miter", pt: "Esquadria" },
    ShellString { id: "ptnd.text.studio.mono_color", en: "Mono / color", pt: "Mono / cor" },
    ShellString { id: "ptnd.text.studio.monochrome", en: "Monochrome", pt: "Monocromático" },
    ShellString { id: "ptnd.text.studio.navigator", en: "Navigator", pt: "Navegador" },
    ShellString { id: "ptnd.text.studio.navigator_hint", en: "Click or drag to pan. Arrow keys move the viewport.", pt: "Clique ou arraste para mover a vista. Use as setas para navegar." },
    ShellString { id: "ptnd.text.studio.navigator_zoom", en: "Navigator", pt: "Navegador" },
    ShellString { id: "ptnd.text.studio.new_tab", en: "New document", pt: "Novo documento" },
    ShellString { id: "ptnd.text.studio.no_assets", en: "Place images to add assets to your document.", pt: "Insira imagens para adicionar recursos ao documento." },
    ShellString { id: "ptnd.text.studio.no_modifiers", en: "No active modifiers", pt: "Nenhum modificador ativo" },
    ShellString { id: "ptnd.text.studio.no_offset", en: "No offset yet.", pt: "Nenhum deslocamento aplicado." },
    ShellString { id: "ptnd.text.studio.no_selection", en: "Nothing selected", pt: "Nada selecionado" },
    ShellString { id: "ptnd.text.studio.node_options", en: "Nodes", pt: "Nós" },
    ShellString { id: "ptnd.text.studio.noise", en: "Noise", pt: "Ruído" },
    ShellString { id: "ptnd.text.studio.none", en: "None", pt: "Nenhum" },
    ShellString { id: "ptnd.text.studio.offset_current", en: "Current offset", pt: "Deslocamento atual" },
    ShellString { id: "ptnd.text.studio.offset_path", en: "Offset path", pt: "Deslocar caminho" },
    ShellString { id: "ptnd.text.studio.offset_zero", en: "0 clears the offset.", pt: "0 remove o deslocamento." },
    ShellString { id: "ptnd.text.studio.opacity", en: "Opacity", pt: "Opacidade" },
    ShellString { id: "ptnd.text.studio.opacity_stops", en: "opacity stops", pt: "marcadores de opacidade" },
    ShellString { id: "ptnd.text.studio.outline_icons", en: "Outline icons", pt: "Ícones de contorno" },
    ShellString { id: "ptnd.text.studio.overwrite", en: "Overwrite", pt: "Substituir" },
    ShellString { id: "ptnd.text.studio.pen_options", en: "Pen", pt: "Caneta" },
    ShellString { id: "ptnd.text.studio.pencil_options", en: "Pencil", pt: "Lápis" },
    ShellString { id: "ptnd.text.studio.pencil_stabilizer", en: "Stabilizer", pt: "Estabilizador" },
    ShellString { id: "ptnd.text.studio.pencil_stabilizer_off", en: "Off", pt: "Desligado" },
    ShellString { id: "ptnd.text.studio.perspective", en: "Perspective", pt: "Perspectiva" },
    ShellString { id: "ptnd.text.studio.perspective_warp", en: "Perspective warp", pt: "Distorção de perspectiva" },
    ShellString { id: "ptnd.text.studio.pink", en: "Pink", pt: "Rosa" },
    ShellString { id: "ptnd.text.studio.pixel", en: "Pixel", pt: "Pixel" },
    ShellString { id: "ptnd.text.studio.pixel_selection", en: "Pixel selection", pt: "Seleção de pixels" },
    ShellString { id: "ptnd.text.studio.pixel_studio", en: "Pixel Studio", pt: "Estúdio de pixels" },
    ShellString { id: "ptnd.text.studio.points", en: "Points", pt: "Pontas" },
    ShellString { id: "ptnd.text.studio.polygon", en: "Polygon", pt: "Polígono" },
    ShellString { id: "ptnd.text.studio.polygon_shape", en: "Polygon", pt: "Polígono" },
    ShellString { id: "ptnd.text.studio.preferences", en: "Preferences", pt: "Preferências" },
    ShellString { id: "ptnd.text.studio.preferences_general", en: "General", pt: "Geral" },
    ShellString { id: "ptnd.text.studio.preferences_performance", en: "Rendering", pt: "Renderização" },
    ShellString { id: "ptnd.text.studio.preferences_shortcuts", en: "Shortcuts", pt: "Atalhos" },
    ShellString { id: "ptnd.text.studio.preferences_tools", en: "Tools", pt: "Ferramentas" },
    ShellString { id: "ptnd.text.studio.preview_description", en: "Composition runs in bounded background workers and updates after edits.", pt: "A composição roda em workers limitados e atualiza após as edições." },
    ShellString { id: "ptnd.text.studio.preview_quality", en: "Canvas preview", pt: "Prévia do canvas" },
    ShellString { id: "ptnd.text.studio.proof", en: "Soft proof", pt: "Prova de cor" },
    ShellString { id: "ptnd.text.studio.properties", en: "Properties", pt: "Propriedades" },
    ShellString { id: "ptnd.text.studio.purple", en: "Purple", pt: "Roxo" },
    ShellString { id: "ptnd.text.studio.quad_warp", en: "Four corner warp", pt: "Deformação de quatro cantos" },
    ShellString { id: "ptnd.text.studio.radius", en: "Radius", pt: "Raio" },
    ShellString { id: "ptnd.text.studio.red", en: "Red", pt: "Vermelho" },
    ShellString { id: "ptnd.text.studio.redo", en: "Redo", pt: "Refazer" },
    ShellString { id: "ptnd.text.studio.rename", en: "Rename layer", pt: "Renomear camada" },
    ShellString { id: "ptnd.text.studio.render_description", en: "Freya / Skia displays immutable document previews.", pt: "Freya / Skia exibe prévias imutáveis do documento." },
    ShellString { id: "ptnd.text.studio.render_engine", en: "Rendering engine", pt: "Motor de renderização" },
    ShellString { id: "ptnd.text.studio.reset_workspace", en: "Reset workspace", pt: "Restaurar área de trabalho" },
    ShellString { id: "ptnd.text.studio.rotation", en: "Rotation", pt: "Rotação" },
    ShellString { id: "ptnd.text.studio.round", en: "Round", pt: "Arredondado" },
    ShellString { id: "ptnd.text.studio.rulers", en: "Rulers", pt: "Réguas" },
    ShellString { id: "ptnd.text.studio.s_curve", en: "S curve", pt: "Curva S" },
    ShellString { id: "ptnd.text.studio.saturation", en: "Saturation", pt: "Saturação" },
    ShellString { id: "ptnd.text.studio.saved", en: "Saved", pt: "Salvo" },
    ShellString { id: "ptnd.text.studio.selection_add", en: "Add", pt: "Adicionar" },
    ShellString { id: "ptnd.text.studio.selection_count", en: "{count} selected", pt: "{count} selecionados" },
    ShellString { id: "ptnd.text.studio.selection_details", en: "Selection", pt: "Seleção" },
    ShellString { id: "ptnd.text.studio.selection_hint", en: "Select an object to inspect its properties.", pt: "Selecione um objeto para inspecionar suas propriedades." },
    ShellString { id: "ptnd.text.studio.selection_intersect", en: "Intersect", pt: "Interseção" },
    ShellString { id: "ptnd.text.studio.selection_replace", en: "Replace", pt: "Substituir" },
    ShellString { id: "ptnd.text.studio.selection_subtract", en: "Subtract", pt: "Subtrair" },
    ShellString { id: "ptnd.text.studio.session_details", en: "Document", pt: "Documento" },
    ShellString { id: "ptnd.text.studio.shape_builder", en: "Shape builder", pt: "Construtor de formas" },
    ShellString { id: "ptnd.text.studio.shape_library", en: "Shape library", pt: "Biblioteca de formas" },
    ShellString { id: "ptnd.text.studio.sharpen", en: "Sharpen", pt: "Nitidez" },
    ShellString { id: "ptnd.text.studio.show_layer", en: "Show layer", pt: "Mostrar camada" },
    ShellString { id: "ptnd.text.studio.show_studio", en: "Show Studio panels", pt: "Mostrar painéis do estúdio" },
    ShellString { id: "ptnd.text.studio.sides", en: "Sides", pt: "Lados" },
    ShellString { id: "ptnd.text.studio.snapping", en: "Snapping", pt: "Encaixe" },
    ShellString { id: "ptnd.text.studio.spot", en: "Spot", pt: "Especial" },
    ShellString { id: "ptnd.text.studio.spot_blue", en: "Studio Blue", pt: "Azul Studio" },
    ShellString { id: "ptnd.text.studio.spot_gold", en: "Studio Gold", pt: "Ouro Studio" },
    ShellString { id: "ptnd.text.studio.spot_red", en: "Studio Red", pt: "Vermelho Studio" },
    ShellString { id: "ptnd.text.studio.square", en: "Square", pt: "Quadrado" },
    ShellString { id: "ptnd.text.studio.star_shape", en: "Star", pt: "Estrela" },
    ShellString { id: "ptnd.text.studio.stroke", en: "Stroke", pt: "Traçado" },
    ShellString { id: "ptnd.text.studio.stroke_width", en: "Stroke", pt: "Traçado" },
    ShellString { id: "ptnd.text.studio.studio", en: "Studio", pt: "Estúdio" },
    ShellString { id: "ptnd.text.studio.subtract", en: "Subtract", pt: "Subtrair" },
    ShellString { id: "ptnd.text.studio.surface_details", en: "Artboard", pt: "Prancheta" },
    ShellString { id: "ptnd.text.studio.surface_objects", en: "Artboard & objects", pt: "Prancheta e objetos" },
    ShellString { id: "ptnd.text.studio.swatch", en: "Swatch", pt: "Amostra" },
    ShellString { id: "ptnd.text.studio.swatches", en: "Swatches", pt: "Amostras" },
    ShellString { id: "ptnd.text.studio.symbols", en: "Shapes", pt: "Formas" },
    ShellString { id: "ptnd.text.studio.system", en: "System", pt: "Sistema" },
    ShellString { id: "ptnd.text.studio.system_palette", en: "System palette", pt: "Paleta do sistema" },
    ShellString { id: "ptnd.text.studio.tasks", en: "Tasks", pt: "Tarefas" },
    ShellString { id: "ptnd.text.studio.teal", en: "Teal", pt: "Verde azulado" },
    ShellString { id: "ptnd.text.studio.temperature", en: "Temperature", pt: "Temperatura" },
    ShellString { id: "ptnd.text.studio.text_options", en: "Text", pt: "Texto" },
    ShellString { id: "ptnd.text.studio.tint", en: "Tint", pt: "Matiz" },
    ShellString { id: "ptnd.text.studio.tool_studio", en: "Tool & Studio", pt: "Ferramenta e Studio" },
    ShellString { id: "ptnd.text.studio.transform", en: "Transform", pt: "Transformação" },
    ShellString { id: "ptnd.text.studio.transparent_gradient", en: "Transparency gradient", pt: "Gradiente de transparência" },
    ShellString { id: "ptnd.text.studio.undo", en: "Undo", pt: "Desfazer" },
    ShellString { id: "ptnd.text.studio.ungroup", en: "Ungroup", pt: "Desagrupar" },
    ShellString { id: "ptnd.text.studio.union", en: "Union", pt: "Unir" },
    ShellString { id: "ptnd.text.studio.unlock_layer", en: "Unlock layer", pt: "Desbloquear camada" },
    ShellString { id: "ptnd.text.studio.unsaved", en: "Unsaved changes", pt: "Alterações não salvas" },
    ShellString { id: "ptnd.text.studio.untitled", en: "Untitled", pt: "Sem título" },
    ShellString { id: "ptnd.text.studio.vector", en: "Vector", pt: "Vetor" },
    ShellString { id: "ptnd.text.studio.vector_crop", en: "Vector crop", pt: "Recorte vetorial" },
    ShellString { id: "ptnd.text.studio.vector_studio", en: "Vector Studio", pt: "Estúdio de vetores" },
    ShellString { id: "ptnd.text.studio.viewport_camera", en: "Viewport & camera", pt: "Vista e câmera" },
    ShellString { id: "ptnd.text.studio.warmer", en: "Warmer +0.1", pt: "Mais quente +0,1" },
    ShellString { id: "ptnd.text.studio.white", en: "White", pt: "Branco" },
    ShellString { id: "ptnd.text.studio.white_balance", en: "White balance", pt: "Balanço de branco" },
    ShellString { id: "ptnd.text.studio.white_less", en: "White −", pt: "Branco −" },
    ShellString { id: "ptnd.text.studio.width", en: "Width", pt: "Largura" },
    ShellString { id: "ptnd.text.studio.yellow", en: "Yellow", pt: "Amarelo" },
    ShellString { id: "ptnd.text.studio.zoom_in", en: "Zoom in", pt: "Ampliar" },
    ShellString { id: "ptnd.text.studio.zoom_out", en: "Zoom out", pt: "Reduzir" },
    ShellString { id: "ptnd.text.studio.search_commands", en: "Search commands…", pt: "Buscar comandos…" },
    ShellString { id: "ptnd.text.studio.no_commands", en: "No commands found.", pt: "Nenhum comando encontrado." },
    ShellString { id: "ptnd.text.studio.name_required", en: "Enter a document name.", pt: "Informe um nome para o documento." },
    ShellString { id: "ptnd.text.studio.point_units", en: "Dimensions, bleed and margins are in points (pt).", pt: "Dimensões, sangria e margens estão em pontos (pt)." },
    ShellString { id: "ptnd.text.studio.deselect", en: "Deselect", pt: "Desselecionar" },
    ShellString { id: "ptnd.text.studio.finish", en: "Finish path", pt: "Concluir caminho" },
    ShellString { id: "ptnd.text.studio.cusp", en: "Cusp", pt: "Cúspide" },
    ShellString { id: "ptnd.text.studio.smooth", en: "Smooth", pt: "Suave" },
    ShellString { id: "ptnd.text.studio.symmetric", en: "Symmetric", pt: "Simétrico" },
    ShellString { id: "ptnd.text.studio.bake_corners", en: "Bake corners", pt: "Fixar cantos" },
    ShellString { id: "ptnd.text.studio.bake_contour", en: "Bake contour", pt: "Fixar contorno" },
    ShellString { id: "ptnd.text.studio.intersection", en: "Intersect", pt: "Interseção" },
    ShellString { id: "ptnd.text.studio.radius_less", en: "Radius −", pt: "Raio −" },
    ShellString { id: "ptnd.text.studio.radius_more", en: "Radius +", pt: "Raio +" },
    ShellString { id: "ptnd.text.studio.points_less", en: "Points −", pt: "Pontas −" },
    ShellString { id: "ptnd.text.studio.points_more", en: "Points +", pt: "Pontas +" },
    ShellString { id: "ptnd.text.studio.sides_less", en: "Sides −", pt: "Lados −" },
    ShellString { id: "ptnd.text.studio.sides_more", en: "Sides +", pt: "Lados +" },
    ShellString { id: "ptnd.text.studio.delete_selection", en: "Clear selection", pt: "Limpar seleção" },
    ShellString { id: "ptnd.text.studio.place_image", en: "Place image…", pt: "Inserir imagem…" },
    ShellString { id: "ptnd.text.studio.hide_assets", en: "Hide assets", pt: "Ocultar recursos" },
    ShellString { id: "ptnd.text.studio.hide_diagnostics", en: "Hide diagnostics", pt: "Ocultar diagnósticos" },
    ShellString { id: "ptnd.text.studio.ui_card", en: "UI card", pt: "Cartão de interface" },
    ShellString { id: "ptnd.text.studio.active_surface", en: "Active surface", pt: "Superfície ativa" },
    ShellString { id: "ptnd.text.studio.object_count", en: "Objects", pt: "Objetos" },
    ShellString { id: "ptnd.text.studio.no_document", en: "No document", pt: "Sem documento" },
    ShellString { id: "ptnd.text.studio.area", en: "Area", pt: "Área" },
    ShellString { id: "ptnd.text.studio.resize_studio", en: "Resize Studio", pt: "Redimensionar estúdio" },
    ShellString { id: "ptnd.text.studio.resize_assets", en: "Resize assets", pt: "Redimensionar recursos" },
    ShellString { id: "ptnd.text.studio.resize_bottom", en: "Resize bottom panel", pt: "Redimensionar painel inferior" },
    ShellString { id: "ptnd.text.studio.hardness", en: "Hardness", pt: "Dureza" },
    ShellString { id: "ptnd.text.studio.precise", en: "Precise", pt: "Preciso" },
    ShellString { id: "ptnd.text.studio.balanced", en: "Balanced", pt: "Equilibrado" },
    ShellString { id: "ptnd.text.studio.radial", en: "Radial", pt: "Radial" },
    ShellString { id: "ptnd.text.studio.typography", en: "Typography", pt: "Tipografia" },
];

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn studio_catalog_ids_are_unique_and_both_languages_are_complete() {
        let mut ids = std::collections::HashSet::new();
        for row in STUDIO_STRINGS {
            assert!(ids.insert(row.id), "duplicate {}", row.id);
            assert!(
                !row.en.trim().is_empty() && !row.pt.trim().is_empty(),
                "{}",
                row.id
            );
        }
    }
}
