class ObjectId:
    @staticmethod
    def generate() -> ObjectId: ...
    @staticmethod
    def parse(text: str) -> ObjectId: ...
    def str(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

class Rectd:
    def __init__(
        self, x: float = 0.0, y: float = 0.0, width: float = 0.0, height: float = 0.0
    ) -> None: ...
    x: float
    y: float
    width: float
    height: float
    def validate(self) -> None: ...

class Affine2D:
    def __init__(self) -> None: ...
    @staticmethod
    def translation(dx: float, dy: float) -> Affine2D: ...
    @staticmethod
    def scale(sx: float, sy: float) -> Affine2D: ...
    def inverted(self) -> Affine2D: ...

class DocumentStore:
    def __init__(self) -> None: ...
    def add_surface(self, name: str, width: float, height: float) -> str: ...
    def object_count(self) -> int: ...
    def add_rectangle(
        self, surface_id: str, name: str, x: float, y: float, width: float, height: float
    ) -> str: ...
    def transform_rectangle(
        self, object_id: str, x: float, y: float, width: float, height: float
    ) -> bool: ...
    def get_rectangle(self, object_id: str) -> tuple[float, float, float, float]: ...
