"""Minimal type stubs for pyclipper (Clipper 1.x).

Only the surface used by the Petunia boolean engine is
declared here; the library ships without py.typed markers.
"""

from collections.abc import Sequence

PFT_EVENODD: int
PFT_NEGATIVE: int
PFT_NONZERO: int
PFT_POSITIVE: int
PT_CLIP: int
PT_SUBJECT: int
CT_UNION: int
CT_DIFFERENCE: int
CT_INTERSECTION: int
CT_XOR: int

Path = Sequence[Sequence[float]]
Paths = Sequence[Path]


class Pyclipper:
    def __init__(
        self,
        subj_fill_type: int = ...,
        clip_fill_type: int = ...,
        use_full_range: bool = ...,
    ) -> None: ...
    def AddPath(self, path: Path, path_type: int, closed: bool) -> bool: ...
    def AddPaths(self, paths: Paths, path_type: int, closed: bool) -> bool: ...
    def Execute(
        self,
        clip_type: int,
        subj_fill_type: int = ...,
        clip_fill_type: int = ...,
    ) -> list[list[tuple[float, float]]]: ...
    def Clear(self) -> None: ...
    def GetBounds(self) -> tuple[int, int, int, int]: ...


class ClipperException(Exception): ...


def CleanPolygon(path: Path, distance: float = ...) -> list[tuple[float, float]]: ...
def CleanPolygons(paths: Paths, distance: float = ...) -> list[list[tuple[float, float]]]: ...
def Area(path: Path) -> float: ...
def Orientation(path: Path) -> bool: ...
def ReversePath(path: Path) -> None: ...
def ReversePaths(paths: Paths) -> None: ...
def SimplifyPolygon(path: Path, fill_type: int = ...) -> list[list[tuple[float, float]]]: ...
def SimplifyPolygons(paths: Paths, fill_type: int = ...) -> list[list[tuple[float, float]]]: ...
def PointInPolygon(pt: Sequence[float], path: Path) -> int: ...
def scale_to_clipper(val: float) -> int: ...
def scale_from_clipper(val: int) -> float: ...
