[package]
name = "petunia_design_color"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
petunia_design_foundation = { path = "../petunia_design_foundation" }
moxcms = "0.9.1"
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest = "1"
