[package]
name = "petunia_design_text"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
petunia_design_foundation = { path = "../petunia_design_foundation" }
petunia_design_color = { path = "../petunia_design_color" }
petunia_design_geometry = { path = "../petunia_design_geometry" }
serde = { workspace = true }
serde_json = { workspace = true }

[lints.rust]
unsafe_code = "forbid"
